name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - master  # Se ejecuta cuando se hace push a la rama main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Extraer el código del repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Instalar Docker Compose
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      # Paso 3: Iniciar sesión en Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Paso 4: Construir la imagen Docker
      - name: Build Docker image
        run: docker-compose build httpd

      # Paso 5: Publicar la imagen en Docker Hub
      - name: Push Docker image
        run: |
          docker tag mi-proyecto_httpd:latest ${{ secrets.DOCKER_HUB_USERNAME }}/httpd:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/httpd:latest
